---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fika-prod-project
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fika-prod-appset
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: "https://github.com/nine-thousand-models/nine-thousand-models-gitops.git"
      revision: main
      files:
      - path: prod/**/config.yaml
  template:
    metadata:
      name: "{{ .path.basename }}-prod"
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: fika-prod
      project: fika-prod-project
      sources:
        - ref: app-values
          repoURL: "https://github.com/nine-thousand-models/nine-thousand-models-gitops.git"
          targetRevision: main
        - helm:
            valueFiles:
              - $app-values/prod/{{ .path.basename }}/config.yaml 
          path: '{{ .chart_path }}'
          repoURL: '{{ .repo_url | default "https://github.com/rhoai-mlops/mlops-helmcharts.git" }}'
          targetRevision: '{{ .target_revision | default "main" }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - Validate=true
